### ISSUE TITLE
branch master reports AttributeError: 'unicode' object has no attribute 'name' in case of multifilesystem

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#272]
Found while testing "master" and storage = multifilesystem (storage = filesystem do not show the error)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/site-packages/radicale/__init__.py", line 310, in __call__
    path, environ.get("HTTP_DEPTH", "0"))
  File "/usr/lib/python2.7/site-packages/radicale/ical.py", line 248, in from_path
    result.extend(collection.components)
  File "/usr/lib/python2.7/site-packages/radicale/ical.py", line 475, in components
    return [item for item in self.items.values() if item.tag in tags]
  File "/usr/lib/python2.7/site-packages/radicale/ical.py", line 462, in items
    self.text, (Event, Todo, Journal, Card, Timezone))
  File "/usr/lib/python2.7/site-packages/radicale/storage/multifilesystem.py", line 79, in text
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
  File "/usr/lib/python2.7/site-packages/radicale/storage/multifilesystem.py", line 79, in <lambda>
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
c

**Comment by jelmer** [comment]
I can also reproduce this.

**Comment by hadogenes** [comment]
I don't understand why this is tagged for Milestone 2.0, this is a bug in which I cannot use version 1.0 (after update from 0.10).
You could just accept #215 and the community could help you to maintain it.

**Comment by liZe** [comment]
Multifilesystem is not "officially" supported, that's why it's not urgent to fix and tagged for 2.0.

I can merge #215 in master and 1.0.x when it's fixed.

**Comment by pbiering** [comment]
This issue is still existing in 1.1.1, so I still can't update from 0.10 which is now a major security issue - any news when Multifilesystem will work again?

**Comment by pbiering** [comment]
Tested master branch and found that from 1.1.1 to master 2 commits were made at Jan 15, 2016 on radicale/storage/multifilesystem.py - looks like now working again.

**Comment by pbiering** [comment]
multifilesystem master branch is only working in case SOGO is used and direct Test.ics directory is addressed.

With Windows Phone it's not working, looks like the browsing of the several calenders in directory user directory is broken and radicale has the meaning, it must be a file:

2016-01-19 09:37:19,119 - WARNING: Error while reading item '/var/lib/radicale/collections/peter.bieringer/Test.ics': IOError(21, 'Is a directory')

and file collections/peter.bieringer.props is created - which should not be the case.

**Comment by liZe** [comment]
Should be fixed now that multifilesystem is the default storage.

**Comment by pbiering** [comment]
Can you please provide a status of the "master" branch in git? I've tried it and had to give up because there were some major changes implemented and it's looking somehow still work-in-progress. Also the new multifilesystem directory layout should be explained somewhere - thank you.

**Comment by liZe** [comment]
@pbiering The current master branch is pretty stable and should be totally usable. As you can see, the storage has changed a lot, it looks like the old multifilesystem but is not compatible with it. You can look at #372 for extra information.

Starting with the default config and empty collections should be as easy as written in the [future doc](http://kozea.github.io/Radicale/tutorial/). There's no official migration guide yet, but if you have a few collections, you can GET them with the old Radicale version and PUT them into the new one.

**Comment by pbiering** [comment]
Current master always logs:
     Skipping component: .Radicale.props
     Skipping collection: .Radicale.props
but as this Radicale's new property file, it should simply skipped but not logged

**Comment by liZe** [comment]
> but as this Radicale's new property file, it should simply skipped but not logged

Thanks for reporting! I've commited the change as 2c938ea.

> reading each item (debug)

Added too in 0c1dbc3.

If you have other changes, you can create pull requests, you'll have your name in the commits!

> how many items are read from directory with duration (to detect bottlenecks on busy/slow systems on info level)

I think that finding bottlenecks with debug messages is a bad idea, as it assumes that you already know where your bottlenecks are (and I often played this game, in the past, each time I lose :wink:). We should rely on profilers, that's their job!
