### ISSUE TITLE
1.0.1: AttributeError: 'unicode' object has no attribute 'name'

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#318]
Found after upgrade from 0.10 to 1.0.1 on a multifilesystem setup:

mod_wsgi (pid=18809): Exception occurred processing WSGI script '/usr/share/radicale/radicale.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/lib/python2.7/site-packages/radicale/__init__.py", line 547, in propfind
    environ["PATH_INFO"], content, collections, user)
  File "/usr/lib/python2.7/site-packages/radicale/xmlutils.py", line 237, in propfind
    response = _propfind_response(path, collection, props, user)
  File "/usr/lib/python2.7/site-packages/radicale/xmlutils.py", line 339, in _propfind_response
    element.text = item.etag
  File "/usr/lib/python2.7/site-packages/radicale/ical.py", line 425, in etag
    md5.update(self.text.encode("utf-8"))
  File "/usr/lib/python2.7/site-packages/radicale/storage/multifilesystem.py", line 89, in text
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
  File "/usr/lib/python2.7/site-packages/radicale/storage/multifilesystem.py", line 89, in <lambda>
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
AttributeError: 'unicode' object has no attribute 'name'

**Comment by hadogenes** [comment]
duplicate of #272

**Comment by liZe** [comment]
Closed as duplicate of #272.
