### ISSUE TITLE
WSGI application doesn't work on Pyhon 3.2

### ISSUE THREAD

**Issue by strayer** [Kozea/Radicale#38]
This will turn up in the logs:

```
GET request at / received
Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/radicale/__init__.py", line 267, in __call__
    "Response content:\n%s" % self.decode(answer, environ))
  File "/usr/lib64/python3.2/site-packages/radicale/__init__.py", line 158, in decode
    return text.decode(charset)
AttributeError: 'str' object has no attribute 'decode'
```

The current line that causes this seems to be here: https://github.com/Kozea/Radicale/blob/master/radicale/__init__.py#L313

The answer should not be a `str`, but a `bytes` object. This will be returned by read() on the wsgi.input stream, and so on. See [PEP-3333](http://www.python.org/dev/peps/pep-3333/#unicode-issues) for reference.

I made on of the worst and most disturbing monkeypatches in my career to get this working for now:

```
import radicale

original_decode = radicale.Application.decode
def python3_wsgi_decode(self, text, environ):
    if isinstance(text, str):
        text = text.encode("utf-8")
    return original_decode(self, text, environ)
radicale.Application.decode = python3_wsgi_decode

radicale.log.start()
application = radicale.Application()
```
